apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "todo-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    - name: authType
      value: "none"
    - name: consumerGroup
      value: "todo-app-backend"
    - name: clientId
      value: "todo-backend"
    - name: maxMessageBytes
      value: "1048576"
    - name: version
      value: "2.8.0"
    - name: initialOffset
      value: "oldest"
    - name: disableTls
      value: "true"
scopes:
  - todo-backend
